version: "3"
services:
    pgadmin:
        image: fenglc/pgadmin4
        environment:
            - DEFAULT_USER=admin
            - DEFAULT_PASSWORD=admin
        ports:
            - 5050:5050
    postgres:
        image: 'postgres'
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        ports:
            - 5432:5432
    server:
        image: server
        build: .
        depends_on:
            - postgres
        ports:
            - 5000:5000
        volumes:
            - ./app/src:/app/src
